import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as cognito from 'aws-cdk-lib/aws-cognito';

/**
 * Properties for CognitoUserPoolStandard
 */
export interface CognitoUserPoolStandardProps {
  /**
   * User Pool name
   *
   * @default - Auto-generated by CDK
   */
  readonly userPoolName?: string;

  /**
   * Enable self sign-up
   *
   * WARUM false als Default?
   * - Sicherheit: Nur Admins können User erstellen
   * - Für öffentliche Apps: selfSignUpEnabled: true
   *
   * @default false
   */
  readonly selfSignUpEnabled?: boolean;

  /**
   * Password policy
   *
   * @default - Secure default policy (min 8 chars, requires uppercase, lowercase, numbers, symbols)
   */
  readonly passwordPolicy?: cognito.PasswordPolicy;

  /**
   * MFA configuration
   *
   * WARUM OFF als Default?
   * - Einfacherer Dev/Test Workflow
   * - Production: OPTIONAL oder REQUIRED empfohlen
   *
   * @default cognito.Mfa.OFF
   */
  readonly mfa?: cognito.Mfa;

  /**
   * User Pool Client name
   *
   * @default - Auto-generated by CDK
   */
  readonly clientName?: string;

  /**
   * Access token validity
   *
   * @default Duration.minutes(60)
   */
  readonly accessTokenValidity?: cdk.Duration;

  /**
   * ID token validity
   *
   * @default Duration.minutes(60)
   */
  readonly idTokenValidity?: cdk.Duration;

  /**
   * Refresh token validity
   *
   * @default Duration.days(30)
   */
  readonly refreshTokenValidity?: cdk.Duration;

  /**
   * Removal policy
   *
   * @default - Auto-detect based on stack name
   */
  readonly removalPolicy?: cdk.RemovalPolicy;
}

/**
 * Cognito User Pool mit Production Best Practices
 *
 * WARUM dieser Construct?
 * 1. Sicherheit: Sichere Password Policy standardmäßig
 * 2. Email-basierte Anmeldung: Nutzerfreundlich
 * 3. Auto-create Client: Sofort einsatzbereit
 *
 * @example
 * ```ts
 * // Einfacher User Pool
 * const userPool = new CognitoUserPoolStandard(this, 'UserPool');
 *
 * // Mit Self Sign-up und MFA
 * const userPool = new CognitoUserPoolStandard(this, 'UserPool', {
 *   selfSignUpEnabled: true,
 *   mfa: cognito.Mfa.OPTIONAL,
 * });
 *
 * // Custom Password Policy
 * const userPool = new CognitoUserPoolStandard(this, 'UserPool', {
 *   passwordPolicy: {
 *     minLength: 12,
 *     requireLowercase: true,
 *     requireUppercase: true,
 *     requireDigits: true,
 *     requireSymbols: false,
 *   },
 * });
 * ```
 */
export class CognitoUserPoolStandard extends Construct {
  /**
   * Der erstellte User Pool
   */
  public readonly userPool: cognito.UserPool;

  /**
   * User Pool ID
   */
  public readonly userPoolId: string;

  /**
   * User Pool ARN
   */
  public readonly userPoolArn: string;

  /**
   * Der erstellte User Pool Client
   */
  public readonly userPoolClient: cognito.UserPoolClient;

  /**
   * User Pool Client ID
   */
  public readonly userPoolClientId: string;

  constructor(scope: Construct, id: string, props: CognitoUserPoolStandardProps = {}) {
    super(scope, id);

    // ========================================
    // 1. REMOVAL POLICY (Environment-aware)
    // ========================================

    const removalPolicy = this.determineRemovalPolicy(props.removalPolicy);

    // ========================================
    // 2. PASSWORD POLICY
    // ========================================

    const passwordPolicy = props.passwordPolicy ?? {
      minLength: 8,
      requireLowercase: true,
      requireUppercase: true,
      requireDigits: true,
      requireSymbols: true,
    };

    // ========================================
    // 3. USER POOL ERSTELLEN
    // ========================================

    this.userPool = new cognito.UserPool(this, 'UserPool', {
      userPoolName: props.userPoolName,

      // Sign-in: Email-basiert
      signInAliases: {
        email: true,
      },

      // Auto-verify Email
      autoVerify: {
        email: true,
      },

      // Self Sign-up
      selfSignUpEnabled: props.selfSignUpEnabled ?? false,

      // Password Policy
      passwordPolicy: passwordPolicy,

      // MFA
      mfa: props.mfa ?? cognito.Mfa.OFF,

      // Lifecycle
      removalPolicy: removalPolicy,
    });

    // ========================================
    // 4. TAGS
    // ========================================

    cdk.Tags.of(this.userPool).add('ManagedBy', 'CDK');
    cdk.Tags.of(this.userPool).add('Construct', 'CognitoUserPoolStandard');

    // ========================================
    // 5. USER POOL CLIENT ERSTELLEN
    // ========================================

    this.userPoolClient = this.userPool.addClient('Client', {
      userPoolClientName: props.clientName,

      // Auth Flows
      authFlows: {
        userSrp: true, // Secure Remote Password
        userPassword: false, // Deprecated
      },

      // Token Validity
      accessTokenValidity: props.accessTokenValidity ?? cdk.Duration.minutes(60),
      idTokenValidity: props.idTokenValidity ?? cdk.Duration.minutes(60),
      refreshTokenValidity: props.refreshTokenValidity ?? cdk.Duration.days(30),

      // Prevent User Existence Errors
      preventUserExistenceErrors: true,
    });

    // ========================================
    // 6. OUTPUTS
    // ========================================

    this.userPoolId = this.userPool.userPoolId;
    this.userPoolArn = this.userPool.userPoolArn;
    this.userPoolClientId = this.userPoolClient.userPoolClientId;
  }

  /**
   * Bestimmt RemovalPolicy basierend auf Stack-Name
   */
  private determineRemovalPolicy(
    customPolicy?: cdk.RemovalPolicy
  ): cdk.RemovalPolicy {
    if (customPolicy) {
      return customPolicy;
    }

    const stackName = cdk.Stack.of(this).stackName.toLowerCase();

    // Production Stack? → RETAIN
    if (
      stackName.includes('prod') ||
      stackName.includes('production') ||
      stackName.includes('live')
    ) {
      return cdk.RemovalPolicy.RETAIN;
    }

    // Dev/Test Stack → DESTROY
    return cdk.RemovalPolicy.DESTROY;
  }
}
