import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as iam from 'aws-cdk-lib/aws-iam';

/**
 * Properties for IamRoleLambdaBasic
 *
 * @example
 * ```ts
 * const props: IamRoleLambdaBasicProps = {
 *   enableXray: true,
 *   extraPolicies: [
 *     new iam.PolicyStatement({
 *       actions: ['s3:GetObject'],
 *       resources: ['arn:aws:s3:::my-bucket/*'],
 *     }),
 *   ],
 * };
 * ```
 */
export interface IamRoleLambdaBasicProps {
  /**
   * Beschreibung der Rolle
   *
   * WARUM wichtig?
   * - Dokumentation in AWS Console
   * - Hilft beim Debugging
   * - Compliance/Auditing
   *
   * @default 'Lambda execution role created by CDK'
   */
  readonly description?: string;

  /**
   * X-Ray Tracing aktivieren?
   *
   * WARUM optional?
   * - X-Ray kostet Geld
   * - Nicht für alle Lambdas nötig
   * - Dev: meist nicht nötig, Prod: empfohlen
   *
   * @default false
   */
  readonly enableXray?: boolean;

  /**
   * Zusätzliche IAM-Policies
   *
   * WARUM Array?
   * - Eine Lambda braucht oft mehrere Berechtigungen
   * - z.B. DynamoDB + S3 + SQS
   * - Flexibel erweiterbar
   *
   * BEISPIEL:
   * ```ts
   * extraPolicies: [
   *   new iam.PolicyStatement({
   *     actions: ['dynamodb:GetItem'],
   *     resources: [table.tableArn],
   *   }),
   * ]
   * ```
   *
   * @default []
   */
  readonly extraPolicies?: iam.PolicyStatement[];

  /**
   * Name der Rolle
   *
   * WARUM optional?
   * - CDK generiert automatisch eindeutigen Namen
   * - Nur setzen wenn Organisation spezifische Namenskonvention hat
   *
   * @default - Auto-generated by CDK
   */
  readonly roleName?: string;
}

/**
 * IAM-Rolle für Lambda mit Least-Privilege Prinzip
 *
 * WARUM dieser Construct?
 * 1. Sicherheit: Minimal nötige Berechtigungen
 * 2. Standardisierung: Überall gleiche Basis-Permissions
 * 3. Wartbarkeit: Zentrale Stelle für Updates
 *
 * WAS macht er?
 * - Erstellt IAM-Rolle für Lambda
 * - Fügt CloudWatch Logs Berechtigungen hinzu
 * - Optional: X-Ray Tracing
 * - Optional: Zusätzliche Policies
 *
 * @example
 * ```ts
 * // Minimal
 * const role = new IamRoleLambdaBasic(this, 'Role');
 *
 * // Mit X-Ray
 * const role = new IamRoleLambdaBasic(this, 'Role', {
 *   enableXray: true,
 * });
 *
 * // Mit zusätzlichen Permissions
 * const role = new IamRoleLambdaBasic(this, 'Role', {
 *   extraPolicies: [
 *     new iam.PolicyStatement({
 *       actions: ['s3:GetObject'],
 *       resources: ['arn:aws:s3:::my-bucket/*'],
 *     }),
 *   ],
 * });
 * ```
 */
export class IamRoleLambdaBasic extends Construct {
  /**
   * Die erstellte IAM-Rolle
   *
   * WARUM public?
   * - Lambda-Function braucht diese Rolle
   * - Andere Constructs müssen darauf zugreifen können
   */
  public readonly role: iam.Role;

  /**
   * ARN der Rolle
   *
   * WARUM extra Property?
   * - Häufig benötigt für Cross-Account Zugriff
   * - Für CloudFormation Outputs
   */
  public readonly roleArn: string;

  /**
   * Name der Rolle
   *
   * WARUM extra Property?
   * - Für CLI-Scripts
   * - Für Debugging in AWS Console
   */
  public readonly roleName: string;

  constructor(scope: Construct, id: string, props: IamRoleLambdaBasicProps = {}) {
    super(scope, id);

    // ========================================
    // 1. VALIDIERUNG
    // ========================================

    this.validateProps(props);

    // ========================================
    // 2. IAM-ROLLE ERSTELLEN
    // ========================================

    this.role = new iam.Role(this, 'Role', {
      // WARUM lambda.amazonaws.com?
      // - Lambda-Service muss diese Rolle "assume" können
      // - Standard für alle Lambda-Funktionen
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),

      // Beschreibung: Wichtig für Dokumentation
      description: props.description ?? 'Lambda execution role created by CDK',

      // Name: Optional, CDK generiert automatisch einen wenn nicht angegeben
      roleName: props.roleName,
    });

    // ========================================
    // 3. CLOUDWATCH LOGS BERECHTIGUNGEN
    // ========================================

    // WARUM diese Permissions?
    // - CreateLogGroup: Erstelle Log-Gruppe (falls nicht vorhanden)
    // - CreateLogStream: Erstelle Log-Stream für Lambda-Invocation
    // - PutLogEvents: Schreibe Log-Einträge

    this.role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: [
          'logs:CreateLogGroup',
          'logs:CreateLogStream',
          'logs:PutLogEvents',
        ],
        // WICHTIG: Resource auf spezifische Log-Gruppe einschränken!
        // Nicht '*' verwenden (wäre unsicher)
        resources: [
          `arn:aws:logs:${cdk.Stack.of(this).region}:${
            cdk.Stack.of(this).account
          }:log-group:/aws/lambda/*`,
        ],
      })
    );

    // ========================================
    // 4. OPTIONAL: X-RAY TRACING
    // ========================================

    // WARUM conditional?
    // - X-Ray kostet Geld
    // - Nicht für alle Lambdas nötig
    // - Nur hinzufügen wenn explizit gewünscht

    if (props.enableXray) {
      this.role.addToPolicy(
        new iam.PolicyStatement({
          effect: iam.Effect.ALLOW,
          actions: [
            'xray:PutTraceSegments', // Sende Trace-Daten
            'xray:PutTelemetryRecords', // Sende Telemetrie
          ],
          resources: ['*'], // X-Ray erlaubt keine Resource-Einschränkung
        })
      );
    }

    // ========================================
    // 5. OPTIONAL: ZUSÄTZLICHE POLICIES
    // ========================================

    // WARUM Array durchgehen?
    // - User kann mehrere Policies hinzufügen
    // - z.B. DynamoDB + S3 + SQS

    if (props.extraPolicies && props.extraPolicies.length > 0) {
      props.extraPolicies.forEach((policy) => {
        this.role.addToPolicy(policy);
      });
    }

    // ========================================
    // 6. TAGS
    // ========================================

    cdk.Tags.of(this.role).add('ManagedBy', 'CDK');
    cdk.Tags.of(this.role).add('Construct', 'IamRoleLambdaBasic');
    cdk.Tags.of(this.role).add('Purpose', 'LambdaExecution');

    // ========================================
    // 7. OUTPUTS
    // ========================================

    this.roleArn = this.role.roleArn;
    this.roleName = this.role.roleName;
  }

  /**
   * Validiert die Props
   *
   * WARUM validieren?
   * - Frühzeitiges Feedback
   * - Bessere Fehlermeldungen
   * - Verhindert AWS API Errors
   */
  private validateProps(props: IamRoleLambdaBasicProps): void {
    // Prüfe Role-Name (AWS Limits)
    if (props.roleName) {
      if (props.roleName.length > 64) {
        throw new Error('Role name must be <= 64 characters');
      }

      // AWS erlaubt nur bestimmte Zeichen
      const validPattern = /^[\w+=,.@-]+$/;
      if (!validPattern.test(props.roleName)) {
        throw new Error('Role name must match pattern: [\\w+=,.@-]+');
      }
    }

    // Prüfe Extra-Policies (sinnvolles Limit)
    if (props.extraPolicies && props.extraPolicies.length > 10) {
      throw new Error('Maximum 10 extra policies allowed (AWS limit)');
    }
  }
}
