import { Construct, Node } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';

/**
 * Properties for ApiGatewayRestApiStandard
 */
export interface ApiGatewayRestApiStandardProps {
  /**
   * API name
   *
   * @default - Auto-generated by CDK
   */
  readonly restApiName?: string;

  /**
   * API description
   *
   * @default - No description
   */
  readonly description?: string;

  /**
   * CORS configuration
   *
   * WARUM optional?
   * - Nicht alle APIs benötigen CORS
   * - Frontend-APIs: CORS aktivieren
   *
   * @default - No CORS
   */
  readonly corsOptions?: apigateway.CorsOptions;

  /**
   * Default stage name
   *
   * WARUM 'prod' als Default?
   * - Standard Production Stage
   * - Kann überschrieben werden für dev/test
   *
   * @default 'prod'
   */
  readonly defaultStageName?: string;

  /**
   * Binary media types
   *
   * BEISPIEL: ['image/png', 'image/jpeg']
   *
   * @default - No binary media types
   */
  readonly binaryMediaTypes?: string[];

  /**
   * Enable CloudWatch logging
   *
   * WARUM true als Default?
   * - Debugging und Monitoring
   * - Production Best Practice
   *
   * @default true
   */
  readonly cloudWatchRole?: boolean;

  /**
   * Deploy options
   *
   * @default - Standard deploy options
   */
  readonly deployOptions?: apigateway.StageOptions;
}

/**
 * API Gateway REST API mit Production Best Practices und IRestApi Interface
 *
 * Diese Klasse implementiert das IRestApi Interface durch Delegation an die
 * innere apigateway.RestApi. Das ermöglicht:
 * - Verwendung überall wo IRestApi erwartet wird
 * - Zugriff auf alle IRestApi Methoden
 * - Best Practices durch opinionated Defaults
 *
 * WARUM dieser Construct?
 * 1. CloudWatch Logging: Immer aktiviert für Debugging
 * 2. CORS Support: Einfach konfigurierbar
 * 3. Deployment: Auto-deploy mit Stage
 *
 * @example
 * ```ts
 * // Einfache REST API
 * const api = new ApiGatewayRestApiStandard(this, 'Api');
 *
 * // Kann überall verwendet werden wo IRestApi erwartet wird
 * const resource = api.root.addResource('todos');
 * resource.addMethod('GET', new apigateway.LambdaIntegration(fn));
 *
 * // Mit CORS für Frontend
 * const api = new ApiGatewayRestApiStandard(this, 'Api', {
 *   corsOptions: {
 *     allowOrigins: apigateway.Cors.ALL_ORIGINS,
 *     allowMethods: apigateway.Cors.ALL_METHODS,
   },
 * });
 * ```
 */
export class ApiGatewayRestApiStandard extends Construct implements apigateway.IRestApi {
  /**
   * Die innere REST API (privat für Delegation)
   */
  private readonly _restApi: apigateway.RestApi;

  // ========================================
  // IRestApi INTERFACE PROPERTIES
  // ========================================

  public readonly restApiId: string;
  public readonly restApiName: string;
  public readonly restApiRootResourceId: string;
  public readonly root: apigateway.IResource;
  public readonly url: string;
  public readonly deploymentStage: apigateway.Stage;
  public readonly env: cdk.ResourceEnvironment;
  public readonly stack: cdk.Stack;
  public readonly node: Node;

  constructor(scope: Construct, id: string, props: ApiGatewayRestApiStandardProps = {}) {
    super(scope, id);

    // ========================================
    // 1. CLOUDWATCH ROLE (für API Gateway Logs)
    // ========================================

    let cloudWatchRole: iam.Role | undefined;

    if (props.cloudWatchRole !== false) {
      cloudWatchRole = new iam.Role(this, 'CloudWatchRole', {
        assumedBy: new iam.ServicePrincipal('apigateway.amazonaws.com'),
        managedPolicies: [
          iam.ManagedPolicy.fromAwsManagedPolicyName(
            'service-role/AmazonAPIGatewayPushToCloudWatchLogs'
          ),
        ],
      });
    }

    // ========================================
    // 2. DEPLOY OPTIONS
    // ========================================

    const deployOptions = props.deployOptions ?? {
      stageName: props.defaultStageName ?? 'prod',
      loggingLevel: apigateway.MethodLoggingLevel.INFO,
      dataTraceEnabled: true,
    };

    // ========================================
    // 3. REST API ERSTELLEN
    // ========================================

    this._restApi = new apigateway.RestApi(this, 'RestApi', {
      restApiName: props.restApiName,
      description: props.description,

      // CORS
      defaultCorsPreflightOptions: props.corsOptions,

      // Deployment
      deploy: true,
      deployOptions: deployOptions,

      // CloudWatch Role
      cloudWatchRole: props.cloudWatchRole !== false,

      // Binary Media Types
      binaryMediaTypes: props.binaryMediaTypes,

      // Default Method Options
      defaultMethodOptions: {
        apiKeyRequired: false,
      },
    });

    // ========================================
    // 4. ACCOUNT-LEVEL CLOUDWATCH ROLE
    // ========================================

    if (cloudWatchRole) {
      new apigateway.CfnAccount(this, 'Account', {
        cloudWatchRoleArn: cloudWatchRole.roleArn,
      });
    }

    // ========================================
    // 5. TAGS
    // ========================================

    cdk.Tags.of(this._restApi).add('ManagedBy', 'CDK');
    cdk.Tags.of(this._restApi).add('Construct', 'ApiGatewayRestApiStandard');

    // ========================================
    // 6. DELEGIERE IRestApi PROPERTIES
    // ========================================

    this.restApiId = this._restApi.restApiId;
    this.restApiName = this._restApi.restApiName;
    this.restApiRootResourceId = this._restApi.restApiRootResourceId;
    this.root = this._restApi.root;
    this.url = this._restApi.url;
    this.deploymentStage = this._restApi.deploymentStage;
    this.env = this._restApi.env;
    this.stack = this._restApi.stack;
    this.node = this._restApi.node;
  }

  // ========================================
  // IRestApi INTERFACE METHODS - URL Generation
  // ========================================

  public urlForPath(path?: string): string {
    return this._restApi.urlForPath(path);
  }

  public arnForExecuteApi(method?: string, path?: string, stage?: string): string {
    return this._restApi.arnForExecuteApi(method, path, stage);
  }

  // ========================================
  // IRestApi INTERFACE METHODS - Grant Permissions
  // ========================================

  public grantExecute(identity: iam.IGrantable, options?: apigateway.ExecuteApiGrantOptions): iam.Grant {
    return (this._restApi as any).grantExecute(identity, options);
  }

  // ========================================
  // IRestApi INTERFACE METHODS - Configuration
  // ========================================

  public addGatewayResponse(id: string, options: apigateway.GatewayResponseOptions): apigateway.GatewayResponse {
    return this._restApi.addGatewayResponse(id, options);
  }

  public addRequestValidator(id: string, props: apigateway.RequestValidatorOptions): apigateway.RequestValidator {
    return this._restApi.addRequestValidator(id, props);
  }

  public addModel(id: string, props: apigateway.ModelOptions): apigateway.Model {
    return this._restApi.addModel(id, props);
  }

  public addApiKey(id: string, options?: apigateway.ApiKeyOptions): apigateway.IApiKey {
    return this._restApi.addApiKey(id, options);
  }

  public addUsagePlan(id: string, props?: apigateway.UsagePlanProps): apigateway.UsagePlan {
    return this._restApi.addUsagePlan(id, props);
  }

  public addDomainName(id: string, options: apigateway.DomainNameOptions): apigateway.DomainName {
    return this._restApi.addDomainName(id, options);
  }

  // ========================================
  // IRestApi INTERFACE METHODS - Metrics
  // ========================================

  public metric(metricName: string, props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metric(metricName, props);
  }

  public metricCacheHitCount(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metricCacheHitCount(props);
  }

  public metricCacheMissCount(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metricCacheMissCount(props);
  }

  public metricClientError(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metricClientError(props);
  }

  public metricServerError(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metricServerError(props);
  }

  public metricCount(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metricCount(props);
  }

  public metricIntegrationLatency(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metricIntegrationLatency(props);
  }

  public metricLatency(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._restApi.metricLatency(props);
  }

  // ========================================
  // REMOVAL POLICY
  // ========================================

  public applyRemovalPolicy(policy: cdk.RemovalPolicy): void {
    this._restApi.applyRemovalPolicy(policy);
  }

  // ========================================
  // ADDITIONAL METHODS
  // ========================================

  /**
   * Access to the underlying apigateway.RestApi for advanced use cases
   *
   * @internal
   */
  public get restApi(): apigateway.RestApi {
    return this._restApi;
  }
}
