import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as iam from 'aws-cdk-lib/aws-iam';

/**
 * Properties for ApiGatewayRestApiStandard
 */
export interface ApiGatewayRestApiStandardProps {
  /**
   * API name
   *
   * @default - Auto-generated by CDK
   */
  readonly restApiName?: string;

  /**
   * API description
   *
   * @default - No description
   */
  readonly description?: string;

  /**
   * CORS configuration
   *
   * WARUM optional?
   * - Nicht alle APIs benötigen CORS
   * - Frontend-APIs: CORS aktivieren
   *
   * @default - No CORS
   */
  readonly corsOptions?: apigateway.CorsOptions;

  /**
   * Default stage name
   *
   * WARUM 'prod' als Default?
   * - Standard Production Stage
   * - Kann überschrieben werden für dev/test
   *
   * @default 'prod'
   */
  readonly defaultStageName?: string;

  /**
   * Binary media types
   *
   * BEISPIEL: ['image/png', 'image/jpeg']
   *
   * @default - No binary media types
   */
  readonly binaryMediaTypes?: string[];

  /**
   * Enable CloudWatch logging
   *
   * WARUM true als Default?
   * - Debugging und Monitoring
   * - Production Best Practice
   *
   * @default true
   */
  readonly cloudWatchRole?: boolean;
}

/**
 * API Gateway REST API mit Production Best Practices
 *
 * WARUM dieser Construct?
 * 1. CloudWatch Logging: Immer aktiviert für Debugging
 * 2. CORS Support: Einfach konfigurierbar
 * 3. Deployment: Auto-deploy mit Stage
 *
 * @example
 * ```ts
 * // Einfache REST API
 * const api = new ApiGatewayRestApiStandard(this, 'Api');
 *
 * // Mit CORS für Frontend
 * const api = new ApiGatewayRestApiStandard(this, 'Api', {
 *   corsOptions: {
 *     allowOrigins: apigateway.Cors.ALL_ORIGINS,
 *     allowMethods: apigateway.Cors.ALL_METHODS,
 *   },
 * });
 *
 * // Lambda Integration
 * api.root.addResource('todos')
 *   .addMethod('GET', new apigateway.LambdaIntegration(listFunction));
 * ```
 */
export class ApiGatewayRestApiStandard extends Construct {
  /**
   * Die erstellte REST API
   */
  public readonly restApi: apigateway.RestApi;

  /**
   * REST API ID
   */
  public readonly restApiId: string;

  /**
   * API URL
   */
  public readonly url: string;

  /**
   * Root Resource (für addResource/addMethod)
   */
  public readonly root: apigateway.IResource;

  constructor(scope: Construct, id: string, props: ApiGatewayRestApiStandardProps = {}) {
    super(scope, id);

    // ========================================
    // 1. CLOUDWATCH ROLE (für API Gateway Logs)
    // ========================================

    let cloudWatchRole: iam.Role | undefined;

    if (props.cloudWatchRole !== false) {
      cloudWatchRole = new iam.Role(this, 'CloudWatchRole', {
        assumedBy: new iam.ServicePrincipal('apigateway.amazonaws.com'),
        managedPolicies: [
          iam.ManagedPolicy.fromAwsManagedPolicyName(
            'service-role/AmazonAPIGatewayPushToCloudWatchLogs'
          ),
        ],
      });
    }

    // ========================================
    // 2. REST API ERSTELLEN
    // ========================================

    this.restApi = new apigateway.RestApi(this, 'RestApi', {
      restApiName: props.restApiName,
      description: props.description,

      // CORS
      defaultCorsPreflightOptions: props.corsOptions,

      // Deployment
      deploy: true,
      deployOptions: {
        stageName: props.defaultStageName ?? 'prod',
        loggingLevel: apigateway.MethodLoggingLevel.INFO,
        dataTraceEnabled: true,
      },

      // CloudWatch Role
      cloudWatchRole: props.cloudWatchRole !== false,

      // Binary Media Types
      binaryMediaTypes: props.binaryMediaTypes,

      // Default Method Options
      defaultMethodOptions: {
        apiKeyRequired: false,
      },
    });

    // ========================================
    // 3. ACCOUNT-LEVEL CLOUDWATCH ROLE
    // ========================================

    if (cloudWatchRole) {
      new apigateway.CfnAccount(this, 'Account', {
        cloudWatchRoleArn: cloudWatchRole.roleArn,
      });
    }

    // ========================================
    // 5. TAGS
    // ========================================

    cdk.Tags.of(this.restApi).add('ManagedBy', 'CDK');
    cdk.Tags.of(this.restApi).add('Construct', 'ApiGatewayRestApiStandard');

    // ========================================
    // 6. OUTPUTS
    // ========================================

    this.restApiId = this.restApi.restApiId;
    this.url = this.restApi.url;
    this.root = this.restApi.root;
  }
}
