import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';

/**
 * Properties for S3BucketSecure
 */
export interface S3BucketSecureProps {
  /**
   * Bucket name
   *
   * @default - Auto-generated by CDK
   */
  readonly bucketName?: string;

  /**
   * Enable versioning
   *
   * WARUM true als Default?
   * - Schutz vor versehentlichem Löschen
   * - Compliance-Anforderungen
   * - Rollback-Möglichkeit
   *
   * @default true
   */
  readonly versioned?: boolean;

  /**
   * Removal policy
   *
   * @default - Auto-detect based on stack name
   */
  readonly removalPolicy?: cdk.RemovalPolicy;

  /**
   * Auto delete objects on bucket removal
   *
   * WARUM false als Default?
   * - Datenschutz
   * - Nur für Dev/Test empfohlen
   *
   * @default false
   */
  readonly autoDeleteObjects?: boolean;

  /**
   * Website index document
   *
   * BEISPIEL: 'index.html'
   *
   * @default - No website hosting
   */
  readonly websiteIndexDocument?: string;

  /**
   * Website error document
   *
   * BEISPIEL: 'error.html'
   *
   * @default - No website hosting
   */
  readonly websiteErrorDocument?: string;

  /**
   * Lifecycle rules
   *
   * @default - No lifecycle rules
   */
  readonly lifecycleRules?: s3.LifecycleRule[];

  /**
   * CORS rules
   *
   * @default - No CORS rules
   */
  readonly cors?: s3.CorsRule[];
}

/**
 * S3 Bucket mit Security Best Practices
 *
 * WARUM dieser Construct?
 * 1. Sicherheit: Block Public Access immer aktiviert
 * 2. Verschlüsselung: SSE-S3 immer aktiviert
 * 3. Versioning: Schutz vor versehentlichem Löschen
 *
 * @example
 * ```ts
 * // Einfacher Bucket
 * const bucket = new S3BucketSecure(this, 'MyBucket');
 *
 * // Static Website Hosting
 * const websiteBucket = new S3BucketSecure(this, 'WebsiteBucket', {
 *   websiteIndexDocument: 'index.html',
 *   websiteErrorDocument: 'error.html',
 * });
 * ```
 */
export class S3BucketSecure extends Construct {
  /**
   * Der erstellte S3 Bucket
   */
  public readonly bucket: s3.Bucket;

  /**
   * ARN des Buckets
   */
  public readonly bucketArn: string;

  /**
   * Name des Buckets
   */
  public readonly bucketName: string;

  /**
   * Website URL (falls Website Hosting aktiviert)
   */
  public readonly bucketWebsiteUrl?: string;

  constructor(scope: Construct, id: string, props: S3BucketSecureProps = {}) {
    super(scope, id);

    // ========================================
    // 1. REMOVAL POLICY (Environment-aware)
    // ========================================

    const removalPolicy = this.determineRemovalPolicy(props.removalPolicy);

    // ========================================
    // 2. WEBSITE CONFIGURATION
    // ========================================

    const websiteConfig =
      props.websiteIndexDocument || props.websiteErrorDocument
        ? {
            indexDocument: props.websiteIndexDocument,
            errorDocument: props.websiteErrorDocument,
          }
        : undefined;

    // ========================================
    // 3. S3 BUCKET ERSTELLEN
    // ========================================

    this.bucket = new s3.Bucket(this, 'Bucket', {
      bucketName: props.bucketName,

      // Security: Block Public Access (immer aktiviert!)
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,

      // Encryption: SSE-S3 (AWS Managed)
      encryption: s3.BucketEncryption.S3_MANAGED,

      // Versioning
      versioned: props.versioned ?? true,

      // Lifecycle
      removalPolicy: removalPolicy,
      autoDeleteObjects: props.autoDeleteObjects ?? false,

      // Website
      websiteIndexDocument: websiteConfig?.indexDocument,
      websiteErrorDocument: websiteConfig?.errorDocument,

      // Lifecycle Rules
      lifecycleRules: props.lifecycleRules,

      // CORS
      cors: props.cors,

      // Security: Enforce SSL
      enforceSSL: true,
    });

    // ========================================
    // 4. TAGS
    // ========================================

    cdk.Tags.of(this.bucket).add('ManagedBy', 'CDK');
    cdk.Tags.of(this.bucket).add('Construct', 'S3BucketSecure');

    // ========================================
    // 5. OUTPUTS
    // ========================================

    this.bucketArn = this.bucket.bucketArn;
    this.bucketName = this.bucket.bucketName;
    this.bucketWebsiteUrl = this.bucket.bucketWebsiteUrl;
  }

  /**
   * Bestimmt RemovalPolicy basierend auf Stack-Name
   */
  private determineRemovalPolicy(
    customPolicy?: cdk.RemovalPolicy
  ): cdk.RemovalPolicy {
    if (customPolicy) {
      return customPolicy;
    }

    const stackName = cdk.Stack.of(this).stackName.toLowerCase();

    // Production Stack? → RETAIN
    if (
      stackName.includes('prod') ||
      stackName.includes('production') ||
      stackName.includes('live')
    ) {
      return cdk.RemovalPolicy.RETAIN;
    }

    // Dev/Test Stack → DESTROY
    return cdk.RemovalPolicy.DESTROY;
  }
}
