import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';

/**
 * Properties for SnsTopicEncrypted
 *
 * @example
 * ```ts
 * const props: SnsTopicEncryptedProps = {
 *   masterKey: myKmsKey,
 *   displayName: 'My Topic',
 *   fifo: true,
 * };
 * ```
 */
export interface SnsTopicEncryptedProps {
  /**
   * KMS Key für Topic-Verschlüsselung
   *
   * WARUM required?
   * - SSE-KMS ist ein Hauptfeature dieses Constructs
   * - Security Best Practice
   * - Compliance-Anforderungen
   *
   * @required
   */
  readonly masterKey: kms.IKey;

  /**
   * Name des Topics
   *
   * WARUM optional?
   * - CDK generiert automatisch eindeutigen Namen
   * - Für FIFO Topics: .fifo wird automatisch angehängt
   *
   * @default - Auto-generated by CDK
   */
  readonly topicName?: string;

  /**
   * Display Name für Topic
   *
   * WARUM wichtig?
   * - Wird in E-Mail-Subscriptions angezeigt
   * - Benutzerfreundlicher als technischer Name
   *
   * @default - No display name
   */
  readonly displayName?: string;

  /**
   * FIFO Topic aktivieren?
   *
   * WARUM optional?
   * - Nicht alle Use Cases brauchen Ordering
   * - FIFO Topics haben geringeren Throughput
   * - Höhere Kosten
   *
   * @default false
   */
  readonly fifo?: boolean;

  /**
   * Content-Based Deduplication
   *
   * WARUM nur für FIFO?
   * - Standard Topics haben keine Deduplication
   * - Verhindert doppelte Messages in FIFO
   *
   * @default false
   */
  readonly contentBasedDeduplication?: boolean;

  /**
   * RemovalPolicy für Topic
   *
   * WARUM wichtig?
   * - Dev: DESTROY (automatisch löschen)
   * - Prod: RETAIN (Subscriptions behalten)
   *
   * @default - Auto-detect based on stack name
   */
  readonly removalPolicy?: cdk.RemovalPolicy;
}

/**
 * SNS Topic mit SSE-KMS Encryption
 *
 * WARUM dieser Construct?
 * 1. Sicherheit: KMS Encryption standardmäßig
 * 2. Standardisierung: Konsistente Topic-Konfiguration
 * 3. Best Practices: FIFO Support, Content-Based Deduplication
 *
 * WAS macht er?
 * - Erstellt SNS Topic mit SSE-KMS
 * - Unterstützt FIFO Topics
 * - Environment-aware RemovalPolicy
 *
 * @example
 * ```ts
 * // Minimal (with KMS key)
 * const topic = new SnsTopicEncrypted(this, 'Topic', {
 *   masterKey: myKmsKey,
 * });
 *
 * // With Display Name
 * const topic = new SnsTopicEncrypted(this, 'Topic', {
 *   masterKey: myKmsKey,
 *   displayName: 'My Notification Topic',
 * });
 *
 * // FIFO Topic
 * const fifoTopic = new SnsTopicEncrypted(this, 'FifoTopic', {
 *   masterKey: myKmsKey,
 *   fifo: true,
 *   contentBasedDeduplication: true,
 * });
 * ```
 */
export class SnsTopicEncrypted extends Construct implements sns.ITopic {
  /**
   * Das innere SNS Topic (privat für Delegation)
   */
  private readonly _topic: sns.Topic;

  /**
   * Store props for interface properties
   */
  private readonly _fifo: boolean;
  private readonly _contentBasedDeduplication: boolean;

  // ========================================
  // ITopic INTERFACE IMPLEMENTATION
  // ========================================

  /**
   * The ARN of the topic
   * @attribute
   */
  public readonly topicArn: string;

  /**
   * The name of the topic
   * @attribute
   */
  public readonly topicName: string;

  /**
   * A KMS Key, either managed by this CDK app, or imported.
   */
  public readonly masterKey?: kms.IKey;

  /**
   * Enables content-based deduplication for FIFO topics.
   * @attribute
   */
  public get contentBasedDeduplication(): boolean {
    return this._contentBasedDeduplication;
  }

  /**
   * Whether this topic is an Amazon SNS FIFO queue.
   * @attribute
   */
  public get fifo(): boolean {
    return this._fifo;
  }

  /**
   * The environment this resource belongs to.
   */
  public readonly env: cdk.ResourceEnvironment;

  /**
   * The stack in which this resource is defined.
   */
  public readonly stack: cdk.Stack;

  constructor(scope: Construct, id: string, props: SnsTopicEncryptedProps) {
    super(scope, id);

    // ========================================
    // 1. VALIDIERUNG
    // ========================================

    this.validateProps(props);

    // ========================================
    // 2. DEFAULTS SETZEN
    // ========================================

    const removalPolicy = props.removalPolicy ?? this.getDefaultRemovalPolicy();
    this._fifo = props.fifo ?? false;
    this._contentBasedDeduplication = props.contentBasedDeduplication ?? false;

    // ========================================
    // 3. TOPIC ERSTELLEN
    // ========================================

    // FIFO Topic: .fifo Suffix automatisch anhängen
    const finalTopicName = props.topicName
      ? this._fifo && !props.topicName.endsWith('.fifo')
        ? `${props.topicName}.fifo`
        : props.topicName
      : undefined;

    this._topic = new sns.Topic(this, 'Topic', {
      topicName: finalTopicName,
      displayName: props.displayName,
      masterKey: props.masterKey,
      fifo: this._fifo,
      contentBasedDeduplication: this._fifo ? this._contentBasedDeduplication : undefined,
    });

    // Apply removal policy
    this._topic.applyRemovalPolicy(removalPolicy);

    // ========================================
    // 4. TAGS
    // ========================================

    cdk.Tags.of(this._topic).add('ManagedBy', 'CDK');
    cdk.Tags.of(this._topic).add('Construct', 'SnsTopicEncrypted');
    cdk.Tags.of(this._topic).add('Encrypted', 'true');
    cdk.Tags.of(this._topic).add('EncryptionType', 'KMS');

    // ========================================
    // 5. DELEGIERE ITopic PROPERTIES
    // ========================================

    this.topicArn = this._topic.topicArn;
    this.topicName = this._topic.topicName;
    this.masterKey = this._topic.masterKey;
    this.env = this._topic.env;
    this.stack = this._topic.stack;
  }

  // ========================================
  // ITopic INTERFACE METHODS
  // ========================================

  /**
   * Subscribe some endpoint to this topic
   */
  public addSubscription(subscription: sns.ITopicSubscription): sns.Subscription {
    return this._topic.addSubscription(subscription);
  }

  /**
   * Adds a statement to the IAM resource policy associated with this topic.
   */
  public addToResourcePolicy(statement: iam.PolicyStatement): iam.AddToResourcePolicyResult {
    return this._topic.addToResourcePolicy(statement);
  }

  /**
   * Grant topic publishing permissions to the given identity
   */
  public grantPublish(identity: iam.IGrantable): iam.Grant {
    return this._topic.grantPublish(identity);
  }

  /**
   * Grant topic subscribing permissions to the given identity
   */
  public grantSubscribe(identity: iam.IGrantable): iam.Grant {
    return this._topic.grantSubscribe(identity);
  }

  // ========================================
  // IResource INTERFACE METHODS
  // ========================================

  /**
   * Apply the given removal policy to this resource
   */
  public applyRemovalPolicy(policy: cdk.RemovalPolicy): void {
    this._topic.applyRemovalPolicy(policy);
  }

  /**
   * Bind this topic to a codestar notification rule target.
   */
  public bindAsNotificationRuleTarget(_scope: Construct): any {
    return this._topic.bindAsNotificationRuleTarget(_scope);
  }

  // ========================================
  // ITopic METRIC METHODS
  // ========================================

  /**
   * Return the given named metric for this Topic
   */
  public metric(metricName: string, props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metric(metricName, props);
  }

  /**
   * Metric for the size of messages published through this topic
   */
  public metricPublishSize(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricPublishSize(props);
  }

  /**
   * The number of messages published to your Amazon SNS topics.
   */
  public metricNumberOfMessagesPublished(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricNumberOfMessagesPublished(props);
  }

  /**
   * The number of messages successfully delivered from your Amazon SNS topics to subscribing endpoints.
   */
  public metricNumberOfNotificationsDelivered(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricNumberOfNotificationsDelivered(props);
  }

  /**
   * The number of messages that Amazon SNS failed to deliver.
   */
  public metricNumberOfNotificationsFailed(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricNumberOfNotificationsFailed(props);
  }

  /**
   * The number of messages that were rejected by subscription filter policies.
   */
  public metricNumberOfNotificationsFilteredOut(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricNumberOfNotificationsFilteredOut(props);
  }

  /**
   * The number of messages that were rejected by subscription filter policies because the messages have no attributes.
   */
  public metricNumberOfNotificationsFilteredOutNoMessageAttributes(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricNumberOfNotificationsFilteredOutNoMessageAttributes(props);
  }

  /**
   * The number of messages that were rejected by subscription filter policies because the messages' attributes are invalid
   */
  public metricNumberOfNotificationsFilteredOutInvalidAttributes(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricNumberOfNotificationsFilteredOutInvalidAttributes(props);
  }

  /**
   * The charges you have accrued since the start of the current calendar month for sending SMS messages.
   */
  public metricSMSMonthToDateSpentUSD(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricSMSMonthToDateSpentUSD(props);
  }

  /**
   * The rate of successful SMS message deliveries.
   */
  public metricSMSSuccessRate(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this._topic.metricSMSSuccessRate(props);
  }

  // ========================================
  // PRIVATE METHODS
  // ========================================

  /**
   * Validiert die Props
   *
   * WARUM validieren?
   * - Frühzeitiges Feedback
   * - Bessere Fehlermeldungen
   * - Verhindert AWS API Errors
   */
  private validateProps(props: SnsTopicEncryptedProps): void {
    // Master Key ist required
    if (!props.masterKey) {
      throw new Error('Master key is required for encrypted SNS topic');
    }

    // Content-Based Deduplication nur für FIFO
    if (props.contentBasedDeduplication && !props.fifo) {
      throw new Error('contentBasedDeduplication can only be enabled for FIFO topics');
    }
  }

  /**
   * Ermittelt die Standard-RemovalPolicy basierend auf Stack-Name
   *
   * WARUM wichtig?
   * - Dev: DESTROY (automatisch löschen, spart Kosten)
   * - Prod: RETAIN (Subscriptions behalten für Compliance)
   *
   * @returns RemovalPolicy.DESTROY für Dev, RETAIN für Prod
   */
  private getDefaultRemovalPolicy(): cdk.RemovalPolicy {
    const stackName = cdk.Stack.of(this).stackName.toLowerCase();

    const devPatterns = ['dev', 'test', 'sandbox', 'local', 'demo'];
    const isDev = devPatterns.some((pattern) => stackName.includes(pattern));

    return isDev ? cdk.RemovalPolicy.DESTROY : cdk.RemovalPolicy.RETAIN;
  }
}
