import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as kms from 'aws-cdk-lib/aws-kms';

/**
 * Properties for SnsTopicEncrypted
 *
 * @example
 * ```ts
 * const props: SnsTopicEncryptedProps = {
 *   masterKey: myKmsKey,
 *   displayName: 'My Topic',
 *   fifo: true,
 * };
 * ```
 */
export interface SnsTopicEncryptedProps {
  /**
   * KMS Key für Topic-Verschlüsselung
   *
   * WARUM required?
   * - SSE-KMS ist ein Hauptfeature dieses Constructs
   * - Security Best Practice
   * - Compliance-Anforderungen
   *
   * @required
   */
  readonly masterKey: kms.IKey;

  /**
   * Name des Topics
   *
   * WARUM optional?
   * - CDK generiert automatisch eindeutigen Namen
   * - Für FIFO Topics: .fifo wird automatisch angehängt
   *
   * @default - Auto-generated by CDK
   */
  readonly topicName?: string;

  /**
   * Display Name für Topic
   *
   * WARUM wichtig?
   * - Wird in E-Mail-Subscriptions angezeigt
   * - Benutzerfreundlicher als technischer Name
   *
   * @default - No display name
   */
  readonly displayName?: string;

  /**
   * FIFO Topic aktivieren?
   *
   * WARUM optional?
   * - Nicht alle Use Cases brauchen Ordering
   * - FIFO Topics haben geringeren Throughput
   * - Höhere Kosten
   *
   * @default false
   */
  readonly fifo?: boolean;

  /**
   * Content-Based Deduplication
   *
   * WARUM nur für FIFO?
   * - Standard Topics haben keine Deduplication
   * - Verhindert doppelte Messages in FIFO
   *
   * @default false
   */
  readonly contentBasedDeduplication?: boolean;

  /**
   * RemovalPolicy für Topic
   *
   * WARUM wichtig?
   * - Dev: DESTROY (automatisch löschen)
   * - Prod: RETAIN (Subscriptions behalten)
   *
   * @default - Auto-detect based on stack name
   */
  readonly removalPolicy?: cdk.RemovalPolicy;
}

/**
 * SNS Topic mit SSE-KMS Encryption
 *
 * WARUM dieser Construct?
 * 1. Sicherheit: KMS Encryption standardmäßig
 * 2. Standardisierung: Konsistente Topic-Konfiguration
 * 3. Best Practices: FIFO Support, Content-Based Deduplication
 *
 * WAS macht er?
 * - Erstellt SNS Topic mit SSE-KMS
 * - Unterstützt FIFO Topics
 * - Environment-aware RemovalPolicy
 *
 * @example
 * ```ts
 * // Minimal (with KMS key)
 * const topic = new SnsTopicEncrypted(this, 'Topic', {
 *   masterKey: myKmsKey,
 * });
 *
 * // With Display Name
 * const topic = new SnsTopicEncrypted(this, 'Topic', {
 *   masterKey: myKmsKey,
 *   displayName: 'My Notification Topic',
 * });
 *
 * // FIFO Topic
 * const fifoTopic = new SnsTopicEncrypted(this, 'FifoTopic', {
 *   masterKey: myKmsKey,
 *   fifo: true,
 *   contentBasedDeduplication: true,
 * });
 * ```
 */
export class SnsTopicEncrypted extends Construct {
  /**
   * Das erstellte SNS Topic
   *
   * WARUM public?
   * - Lambda-Functions brauchen das Topic für Subscriptions
   * - Andere Constructs müssen Permissions hinzufügen
   */
  public readonly topic: sns.Topic;

  /**
   * ARN des Topics
   *
   * WARUM extra Property?
   * - Häufig benötigt für IAM Policies
   * - Für CloudFormation Outputs
   */
  public readonly topicArn: string;

  /**
   * Name des Topics
   *
   * WARUM extra Property?
   * - Benötigt für SDK-Calls (publish)
   * - Für Application Config
   */
  public readonly topicName: string;

  constructor(scope: Construct, id: string, props: SnsTopicEncryptedProps) {
    super(scope, id);

    // ========================================
    // 1. VALIDIERUNG
    // ========================================

    this.validateProps(props);

    // ========================================
    // 2. DEFAULTS SETZEN
    // ========================================

    const removalPolicy = props.removalPolicy ?? this.getDefaultRemovalPolicy();
    const fifo = props.fifo ?? false;
    const contentBasedDeduplication = props.contentBasedDeduplication ?? false;

    // ========================================
    // 3. TOPIC ERSTELLEN
    // ========================================

    // FIFO Topic: .fifo Suffix automatisch anhängen
    const finalTopicName = props.topicName
      ? fifo && !props.topicName.endsWith('.fifo')
        ? `${props.topicName}.fifo`
        : props.topicName
      : undefined;

    this.topic = new sns.Topic(this, 'Topic', {
      topicName: finalTopicName,
      displayName: props.displayName,
      masterKey: props.masterKey,
      fifo,
      contentBasedDeduplication: fifo ? contentBasedDeduplication : undefined,
    });

    // Apply removal policy
    this.topic.applyRemovalPolicy(removalPolicy);

    // ========================================
    // 4. TAGS
    // ========================================

    cdk.Tags.of(this.topic).add('ManagedBy', 'CDK');
    cdk.Tags.of(this.topic).add('Construct', 'SnsTopicEncrypted');
    cdk.Tags.of(this.topic).add('Encrypted', 'true');
    cdk.Tags.of(this.topic).add('EncryptionType', 'KMS');

    // ========================================
    // 5. OUTPUTS
    // ========================================

    this.topicArn = this.topic.topicArn;
    this.topicName = this.topic.topicName;
  }

  /**
   * Validiert die Props
   *
   * WARUM validieren?
   * - Frühzeitiges Feedback
   * - Bessere Fehlermeldungen
   * - Verhindert AWS API Errors
   */
  private validateProps(props: SnsTopicEncryptedProps): void {
    // Master Key ist required
    if (!props.masterKey) {
      throw new Error('Master key is required for encrypted SNS topic');
    }

    // Content-Based Deduplication nur für FIFO
    if (props.contentBasedDeduplication && !props.fifo) {
      throw new Error('contentBasedDeduplication can only be enabled for FIFO topics');
    }
  }

  /**
   * Ermittelt die Standard-RemovalPolicy basierend auf Stack-Name
   *
   * WARUM wichtig?
   * - Dev: DESTROY (automatisch löschen, spart Kosten)
   * - Prod: RETAIN (Subscriptions behalten für Compliance)
   *
   * @returns RemovalPolicy.DESTROY für Dev, RETAIN für Prod
   */
  private getDefaultRemovalPolicy(): cdk.RemovalPolicy {
    const stackName = cdk.Stack.of(this).stackName.toLowerCase();

    const devPatterns = ['dev', 'test', 'sandbox', 'local', 'demo'];
    const isDev = devPatterns.some((pattern) => stackName.includes(pattern));

    return isDev ? cdk.RemovalPolicy.DESTROY : cdk.RemovalPolicy.RETAIN;
  }
}
