import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';

/**
 * Properties for LambdaFunctionSecure
 */
export interface LambdaFunctionSecureProps {
  /**
   * Function name
   *
   * @default - Auto-generated by CDK
   */
  readonly functionName?: string;

  /**
   * Runtime environment
   *
   * BEISPIEL:
   * - lambda.Runtime.PYTHON_3_11
   * - lambda.Runtime.NODEJS_20_X
   */
  readonly runtime: lambda.Runtime;

  /**
   * Handler function
   *
   * BEISPIEL:
   * - Python: 'index.handler'
   * - Node.js: 'index.handler'
   */
  readonly handler: string;

  /**
   * Code source
   *
   * BEISPIEL:
   * - lambda.Code.fromAsset('../backend')
   * - lambda.Code.fromInline('def handler...')
   */
  readonly code: lambda.Code;

  /**
   * IAM Role
   *
   * WARUM optional?
   * - Wird automatisch erstellt wenn nicht angegeben
   * - Ermöglicht Wiederverwendung von IamRoleLambdaBasic
   *
   * @default - Auto-created with basic CloudWatch permissions
   */
  readonly role?: iam.IRole;

  /**
   * Environment variables
   *
   * BEISPIEL:
   * ```ts
   * environment: {
   *   TABLE_NAME: table.tableName,
   *   STAGE: 'prod',
   * }
   * ```
   *
   * @default - No environment variables
   */
  readonly environment?: { [key: string]: string };

  /**
   * Timeout
   *
   * WARUM 3 Sekunden als Default?
   * - Kostenoptimiert
   * - Verhindert lange laufende Functions
   * - Kann bei Bedarf erhöht werden
   *
   * @default Duration.seconds(3)
   */
  readonly timeout?: cdk.Duration;

  /**
   * Memory size (MB)
   *
   * WARUM 128 MB als Default?
   * - Free Tier: 400,000 GB-seconds pro Monat
   * - Kostenoptimiert für einfache Functions
   * - Kann bei Bedarf erhöht werden
   *
   * @default 128
   */
  readonly memorySize?: number;

  /**
   * Reserved concurrent executions
   *
   * WARUM optional?
   * - Nur nötig für Throttling Control
   * - Kostet nichts, aber limitiert Skalierung
   *
   * @default - No limit
   */
  readonly reservedConcurrentExecutions?: number;

  /**
   * X-Ray tracing
   *
   * WARUM optional?
   * - Kostet extra (minimal)
   * - Nur für Prod empfohlen
   *
   * @default - No tracing
   */
  readonly tracing?: lambda.Tracing;

  /**
   * Log retention (Tage)
   *
   * WARUM 14 Tage als Default?
   * - Kostenoptimiert
   * - Ausreichend für Debugging
   *
   * @default logs.RetentionDays.TWO_WEEKS
   */
  readonly logRetention?: logs.RetentionDays;

  /**
   * Description
   *
   * @default - No description
   */
  readonly description?: string;
}

/**
 * Lambda Function mit Production Best Practices
 *
 * WARUM dieser Construct?
 * 1. Kostenoptimierung: Niedrige Defaults (128MB, 3s timeout)
 * 2. Sicherheit: Auto-create IAM Role mit Least Privilege
 * 3. Observability: Auto-create Log Group mit Retention
 *
 * @example
 * ```ts
 * // Mit auto-created Role
 * const fn = new LambdaFunctionSecure(this, 'TodoHandler', {
 *   runtime: lambda.Runtime.PYTHON_3_11,
 *   handler: 'handlers/create_todo.handler',
 *   code: lambda.Code.fromAsset('../backend'),
 *   environment: {
 *     TABLE_NAME: table.tableName,
 *   },
 * });
 *
 * // Mit custom Role (für mehr Berechtigungen)
 * const role = new IamRoleLambdaBasic(this, 'Role', {
 *   enableXray: true,
 *   extraPolicies: [
 *     new iam.PolicyStatement({
 *       actions: ['dynamodb:*'],
 *       resources: [table.tableArn],
 *     }),
 *   ],
 * });
 *
 * const fn = new LambdaFunctionSecure(this, 'Handler', {
 *   runtime: lambda.Runtime.PYTHON_3_11,
 *   handler: 'index.handler',
 *   code: lambda.Code.fromAsset('../backend'),
 *   role: role.role,
 * });
 * ```
 */
export class LambdaFunctionSecure extends Construct {
  /**
   * Die erstellte Lambda Function
   */
  public readonly function: lambda.Function;

  /**
   * ARN der Function
   */
  public readonly functionArn: string;

  /**
   * Name der Function
   */
  public readonly functionName: string;

  /**
   * IAM Role der Function
   */
  public readonly role: iam.IRole;

  /**
   * Log Group der Function
   */
  public readonly logGroup?: logs.ILogGroup;

  constructor(scope: Construct, id: string, props: LambdaFunctionSecureProps) {
    super(scope, id);

    // ========================================
    // 1. IAM ROLE (Auto-create if not provided)
    // ========================================

    const role =
      props.role ??
      new iam.Role(this, 'Role', {
        assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
        managedPolicies: [
          iam.ManagedPolicy.fromAwsManagedPolicyName(
            'service-role/AWSLambdaBasicExecutionRole'
          ),
        ],
      });

    this.role = role;

    // ========================================
    // 2. LAMBDA FUNCTION
    // ========================================

    this.function = new lambda.Function(this, 'Function', {
      functionName: props.functionName,
      runtime: props.runtime,
      handler: props.handler,
      code: props.code,
      role: role,
      environment: props.environment,
      timeout: props.timeout ?? cdk.Duration.seconds(3),
      memorySize: props.memorySize ?? 128,
      reservedConcurrentExecutions: props.reservedConcurrentExecutions,
      tracing: props.tracing,
      description: props.description,
      logRetention: props.logRetention ?? logs.RetentionDays.TWO_WEEKS,
    });

    // ========================================
    // 3. TAGS
    // ========================================

    cdk.Tags.of(this.function).add('ManagedBy', 'CDK');
    cdk.Tags.of(this.function).add('Construct', 'LambdaFunctionSecure');

    // ========================================
    // 4. OUTPUTS
    // ========================================

    this.functionArn = this.function.functionArn;
    this.functionName = this.function.functionName;

    // LogGroup ist automatisch via logRetention erstellt
    if (props.logRetention) {
      this.logGroup = logs.LogGroup.fromLogGroupName(
        this,
        'LogGroup',
        `/aws/lambda/${this.function.functionName}`
      );
    }
  }
}
